-- ============================================================================
-- SEED: Platform AI Agents (Hardened)
-- Purpose:
--   Populate public.ai_agents with the core agents needed by IgnitiaOS.
--
-- Safety:
--   - Idempotent by slug (WHERE NOT EXISTS).
--   - Uses dollar-quoted text for prompts and descriptions.
--   - Uses explicit jsonb casts for tools, tool_configs, and workflow.
--   - Uses ASCII-only icon values to avoid encoding issues.
-- ============================================================================

WITH seed AS (
  SELECT *
  FROM (
    VALUES
      (
        $$Website Audit Specialist$$,
        $$Runs full website audits with technical, UX, SEO, and conversion recommendations.$$,
        $$/images/agents/website-audit-specialist.png$$,
        $$Audit$$,
        $$active$$,
        $$gpt-5$$,
        $$You are an elite website audit specialist. Analyze structure, SEO, UX, performance, messaging, and conversion paths. Provide prioritized recommendations with clear expected impact.$$,
        0.50::numeric,
        8000,
        $$audit$$,
        $$website-audit-specialist$$,
        $$2.0.0$$,
        $$openai$$,
        $$high$$,
        $$Markdown$$,
        $$internal$$,
        '["browser","playwright","vision","ocr","firecrawl"]'::jsonb,
        '{"browser":{"timeout":90,"retries":2},"playwright":{"timeout":120,"retries":2},"firecrawl":{"timeout":90,"retries":2}}'::jsonb,
        '[{"id":"trigger-1","type":"trigger","title":"Trigger","config":{"timeout":30}},{"id":"crawl-1","type":"browser","title":"Crawl Site","config":{"timeout":90,"input_variable":"{{website}}","output_variable":"{{crawl_result}}"}},{"id":"analyze-1","type":"llm","title":"Generate Audit","config":{"timeout":120,"prompt":"Create a complete audit report from crawl_result."}},{"id":"report-1","type":"report","title":"Generate Report","config":{"timeout":60}}]'::jsonb,
        $$analyst$$
      ),
      (
        $$SEO Growth Analyst$$,
        $$Finds rankings opportunities, technical SEO blockers, and content gap priorities.$$,
        $$/images/agents/seo-growth-analyst.png$$,
        $$SEO$$,
        $$active$$,
        $$gpt-5$$,
        $$You are an SEO growth analyst. Identify technical SEO issues, keyword opportunities, intent mismatches, and internal linking opportunities. Return plans in execution order.$$,
        0.40::numeric,
        7000,
        $$seo$$,
        $$seo-growth-analyst$$,
        $$2.0.0$$,
        $$openai$$,
        $$high$$,
        $$Markdown$$,
        $$internal$$,
        '["browser","firecrawl","tavily"]'::jsonb,
        '{"browser":{"timeout":90,"retries":2},"firecrawl":{"timeout":90,"retries":2},"tavily":{"timeout":60,"retries":2}}'::jsonb,
        '[{"id":"trigger-1","type":"trigger","title":"Trigger","config":{"timeout":30}},{"id":"research-1","type":"browser","title":"SERP Research","config":{"timeout":90}},{"id":"analyze-1","type":"llm","title":"SEO Analysis","config":{"timeout":120}},{"id":"report-1","type":"report","title":"SEO Roadmap","config":{"timeout":60}}]'::jsonb,
        $$analyst$$
      ),
      (
        $$Lead Qualification Agent$$,
        $$Scores inbound leads, enriches contact context, and routes leads to the right pipeline stage.$$,
        $$/images/agents/lead-qualification-agent.png$$,
        $$Sales$$,
        $$active$$,
        $$gpt-5$$,
        $$You are a lead qualification engine. Evaluate fit, urgency, budget signals, and intent. Assign lead scores and recommended next actions.$$,
        0.30::numeric,
        5000,
        $$lead$$,
        $$lead-qualification-agent$$,
        $$2.0.0$$,
        $$openai$$,
        $$medium$$,
        $$JSON$$,
        $$internal$$,
        '["browser","supabase","postgres","webhook"]'::jsonb,
        '{"supabase":{"timeout":45,"retries":2},"postgres":{"timeout":45,"retries":2},"webhook":{"timeout":30,"retries":2}}'::jsonb,
        '[{"id":"trigger-1","type":"trigger","title":"Trigger","config":{"timeout":30}},{"id":"enrich-1","type":"browser","title":"Enrich Lead","config":{"timeout":60}},{"id":"score-1","type":"llm","title":"Score Lead","config":{"timeout":60}},{"id":"db-1","type":"database","title":"Persist Score","config":{"timeout":45}}]'::jsonb,
        $$analyst$$
      ),
      (
        $$Outreach Automation Agent$$,
        $$Builds and executes personalized follow-up sequences across lead segments.$$,
        $$/images/agents/outreach-automation-agent.png$$,
        $$Automation$$,
        $$active$$,
        $$gpt-5$$,
        $$You are an outreach automation specialist. Build concise personalized outreach sequences, adapt by persona, and optimize for reply rate and conversion quality.$$,
        0.70::numeric,
        6000,
        $$outreach$$,
        $$outreach-automation-agent$$,
        $$2.0.0$$,
        $$openai$$,
        $$medium$$,
        $$Markdown$$,
        $$internal$$,
        '["email","slack","webhook","queue"]'::jsonb,
        '{"email":{"timeout":45,"retries":3},"queue":{"timeout":30,"retries":2},"webhook":{"timeout":30,"retries":2}}'::jsonb,
        '[{"id":"trigger-1","type":"trigger","title":"Trigger","config":{"timeout":30}},{"id":"compose-1","type":"llm","title":"Compose Sequence","config":{"timeout":90}},{"id":"email-1","type":"email","title":"Send Email","config":{"timeout":45}},{"id":"loop-1","type":"loop","title":"Follow-up Loop","config":{"timeout":30}}]'::jsonb,
        $$consultant$$
      ),
      (
        $$Funnel Conversion Optimizer$$,
        $$Analyzes funnel drop-offs and proposes high-impact conversion improvements.$$,
        $$/images/agents/funnel-conversion-optimizer.png$$,
        $$Marketing$$,
        $$active$$,
        $$gpt-5$$,
        $$You are a conversion optimization expert. Detect friction in funnel steps, identify message mismatches, and propose prioritized test hypotheses with estimated lift.$$,
        0.60::numeric,
        6500,
        $$funnel$$,
        $$funnel-conversion-optimizer$$,
        $$2.0.0$$,
        $$openai$$,
        $$high$$,
        $$Markdown$$,
        $$internal$$,
        '["browser","playwright","vision","supabase"]'::jsonb,
        '{"browser":{"timeout":90,"retries":2},"playwright":{"timeout":120,"retries":2},"supabase":{"timeout":45,"retries":2}}'::jsonb,
        '[{"id":"trigger-1","type":"trigger","title":"Trigger","config":{"timeout":30}},{"id":"browse-1","type":"browser","title":"Explore Funnel","config":{"timeout":90}},{"id":"llm-1","type":"llm","title":"Generate Optimizations","config":{"timeout":120}},{"id":"report-1","type":"report","title":"CRO Plan","config":{"timeout":60}}]'::jsonb,
        $$marketing$$
      ),
      (
        $$Landing Page Content Engine$$,
        $$Generates persuasive page copy, section messaging, and CTA variants by offer type.$$,
        $$/images/agents/landing-page-content-engine.png$$,
        $$Branding$$,
        $$active$$,
        $$gpt-5$$,
        $$You are a senior conversion copywriter. Produce clear persuasive high-intent landing page copy aligned to pains, promise, proof, and CTA clarity.$$,
        0.80::numeric,
        7000,
        $$content$$,
        $$landing-page-content-engine$$,
        $$2.0.0$$,
        $$openai$$,
        $$medium$$,
        $$Markdown$$,
        $$internal$$,
        '["browser","filesystem","pdf"]'::jsonb,
        '{"filesystem":{"timeout":45,"retries":2},"pdf":{"timeout":45,"retries":2}}'::jsonb,
        '[{"id":"trigger-1","type":"trigger","title":"Trigger","config":{"timeout":30}},{"id":"research-1","type":"browser","title":"Offer Research","config":{"timeout":60}},{"id":"write-1","type":"llm","title":"Write Copy","config":{"timeout":120}},{"id":"report-1","type":"report","title":"Copy Pack","config":{"timeout":60}}]'::jsonb,
        $$marketing$$
      ),
      (
        $$Revenue Operations Analyst$$,
        $$Monitors performance metrics, identifies bottlenecks, and recommends execution priorities.$$,
        $$/images/agents/revenue-operations-analyst.png$$,
        $$Business$$,
        $$active$$,
        $$gpt-5$$,
        $$You are a RevOps analyst. Synthesize pipeline, conversion, and campaign metrics into strategic insights and weekly action plans.$$,
        0.40::numeric,
        6000,
        $$revops$$,
        $$revenue-operations-analyst$$,
        $$2.0.0$$,
        $$openai$$,
        $$high$$,
        $$Markdown$$,
        $$internal$$,
        '["supabase","postgres","filesystem"]'::jsonb,
        '{"supabase":{"timeout":45,"retries":2},"postgres":{"timeout":45,"retries":2}}'::jsonb,
        '[{"id":"trigger-1","type":"trigger","title":"Trigger","config":{"timeout":30}},{"id":"db-1","type":"database","title":"Fetch Metrics","config":{"timeout":60}},{"id":"llm-1","type":"llm","title":"Analyze Trends","config":{"timeout":90}},{"id":"report-1","type":"report","title":"RevOps Summary","config":{"timeout":60}}]'::jsonb,
        $$analyst$$
      ),
      (
        $$Client Success Concierge$$,
        $$Creates proactive client updates, risk flags, and next best actions for account growth.$$,
        $$/images/agents/client-success-concierge.png$$,
        $$Business$$,
        $$active$$,
        $$gpt-5$$,
        $$You are a client success concierge. Summarize outcomes, detect risk signals early, and propose clear next steps to improve retention and expansion.$$,
        0.60::numeric,
        5500,
        $$success$$,
        $$client-success-concierge$$,
        $$2.0.0$$,
        $$openai$$,
        $$medium$$,
        $$Markdown$$,
        $$internal$$,
        '["supabase","email","slack"]'::jsonb,
        '{"supabase":{"timeout":45,"retries":2},"email":{"timeout":45,"retries":2},"slack":{"timeout":30,"retries":2}}'::jsonb,
        '[{"id":"trigger-1","type":"trigger","title":"Trigger","config":{"timeout":30}},{"id":"db-1","type":"database","title":"Read Account Data","config":{"timeout":60}},{"id":"llm-1","type":"llm","title":"Generate Success Plan","config":{"timeout":90}},{"id":"email-1","type":"email","title":"Send Update","config":{"timeout":45}}]'::jsonb,
        $$consultant$$
      )
  ) AS t(
    name,
    description,
    avatar,
    category,
    status,
    model,
    system_prompt,
    temperature,
    max_tokens,
    icon,
    slug,
    version,
    provider,
    reasoning,
    response_format,
    visibility,
    tools,
    tool_configs,
    workflow,
    personality_preset
  )
)
INSERT INTO public.ai_agents (
  name,
  description,
  avatar,
  category,
  status,
  model,
  system_prompt,
  temperature,
  max_tokens,
  icon,
  slug,
  version,
  provider,
  reasoning,
  response_format,
  visibility,
  tools,
  tool_configs,
  workflow,
  personality_preset
)
SELECT
  s.name,
  s.description,
  s.avatar,
  s.category,
  s.status,
  s.model,
  s.system_prompt,
  s.temperature,
  s.max_tokens,
  s.icon,
  s.slug,
  s.version,
  s.provider,
  s.reasoning,
  s.response_format,
  s.visibility,
  s.tools,
  s.tool_configs,
  s.workflow,
  s.personality_preset
FROM seed s
WHERE NOT EXISTS (
  SELECT 1
  FROM public.ai_agents a
  WHERE a.slug = s.slug
);
